---
# ==============================================================================
# Extra_Vars
# ==============================================================================
# aws_region: "ap-northeast-1"
# aws_keypair_name: "patch-demo-key"
# rhsm_username: "your_redhat_login_user"
# rhsm_passwd: "your_redhat_password"
# mysql_root_passwd: "YourStrongRootPassword123!"
# mysql_wp_passwd: "YourStrongWPPassword123!"
# wp_admin_password: "YourWPAdminPassword123!"
# ==============================================================================
# Play 1: AWS 上に Managed VM (dev/prod) をプロビジョニング
# ==============================================================================
- name: Create managed VMs
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "{{ aws_region | default('ap-northeast-1') }}"
    aws_keypair_name: "{{ aws_keypair_name | default('patch-demo-key') }}"

  tasks:
    - name: Fail if required variables not defined
      ansible.builtin.assert:
        that:
          - aws_region is defined
          - aws_vpc_subnet_name is defined
          - aws_securitygroup_name is defined
          - aws_keypair_name is defined
          - aws_managed_instance is defined
          - managed_vms_name_prefix is defined
          - managed_vms_type is defined
          - managed_vms_environment is defined
          - purpose is defined
        fail_msg: "Required variables not set. Please check group_vars or Extra Vars."

    - name: Check if the VM is already provisioned
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ managed_vms_name_prefix }}-*"
          "tag:type": "{{ managed_vms_type }}"
          "tag:purpose": "{{ purpose }}"
          instance-state-name:
            - pending
            - running
            - shutting-down
            - stopping
            - stopped
        region: "{{ aws_region }}"
      register: existing_vms

    - name: Output the IP of existing VM
      ansible.builtin.debug:
        msg:
          - "Managed instances look like already provisioned."
          - "Private IP: {{ item.private_ip_address }}"
      loop: "{{ existing_vms.instances }}"
      when: existing_vms.instances is defined and existing_vms.instances | length > 0

    - name: Create Instances
      when: existing_vms.instances | length == 0
      block:
        - name: Get subnet info
          amazon.aws.ec2_vpc_subnet_info:
            region: "{{ aws_region }}"
            filters:
              "tag:Name": "{{ aws_vpc_subnet_name }}"
          register: aws_subnet
          when: aws_subnet_id is not defined

        - name: Save subnet id
          ansible.builtin.set_fact:
            aws_subnet_id: "{{ aws_subnet.subnets | map(attribute='id') | list | last }}"
          when: aws_subnet_id is not defined

        - name: Create the instance
          amazon.aws.ec2_instance:
            key_name: "{{ aws_keypair_name }}"
            instance_type: "{{ aws_managed_instance[item].size }}"
            image_id: "{{ aws_managed_instance[item].ami }}"
            region: "{{ aws_region }}"
            security_groups:
              - "{{ aws_securitygroup_name }}"
            vpc_subnet_id: "{{ aws_subnet_id }}"
            network_interfaces:
              - assign_public_ip: true
            tags:
              Name: "{{ managed_vms_name_prefix }}-{{ item }}"
              environment: "{{ item }}"
              type: "{{ managed_vms_type }}"
              purpose: "{{ purpose }}"
            volumes:
              - device_name: /dev/sda1
                ebs:
                  volume_size: 100
                  delete_on_termination: true
            wait: true
          register: aws_ec2_instance
          loop: "{{ managed_vms_environment }}"

        - name: Output the IP of new VM
          ansible.builtin.debug:
            msg:
              - "Public IP for new instance: {{ item.instances[0].public_ip_address | default('') }}"
              - "Private IP for new instance: {{ item.instances[0].private_ip_address | default('') }}"
          loop: "{{ aws_ec2_instance.results }}"
          when: aws_ec2_instance.results is defined and aws_ec2_instance.results | length > 0

        - name: Wait for EC2 instance to be ready
          ansible.builtin.wait_for:
            delay: 30
            host: "{{ item.instances[0].public_ip_address }}"
            port: 22
            state: started
            timeout: 300
          loop: "{{ aws_ec2_instance.results }}"
          when: aws_ec2_instance.results is defined and aws_ec2_instance.results | length > 0

        - name: Add the instance to in-memory inventory groups
          ansible.builtin.add_host:
            name: "{{ item.instances[0].public_ip_address }}"
            groups: "{{ item.instances[0].tags.environment }}"
            ansible_user: "ec2-user"
          loop: "{{ aws_ec2_instance.results }}"
          when: aws_ec2_instance.results is defined and aws_ec2_instance.results | length > 0


# ==============================================================================
# Play 2: Dev サーバーのミドルウェア/Wordpress 設定
# ==============================================================================
- name: Configure dev server
  hosts: dev
  become: true
  gather_facts: true
  roles:
    - managed


# ==============================================================================
# Play 3: Prod サーバーのミドルウェア/Wordpress 設定
# ==============================================================================
- name: Configure prod server
  hosts: prod
  become: true
  gather_facts: true
  roles:
    - managed
