---
# Create Job_Template
# ----------------------------------------------
# Extra_vars: 
# ----------------------------------------------
# - inventory_name: Patch_Demo
# - project_name: Patch_Lightspeed_Demo
# - execution_environment_name: Default execution environment
# - organization_name: Default
# - aws_credential_name: aws_cred
# - aws_ssh_credential_name: aws_key
# - github_ssh_credential_name: GitHub Push Credential
# - git_repository_url: git@github.com:kforetas/patching-rhel-lightspeed-demo.git
# - label_environment: environment
# - label_scan: scan
# - label_patch: patch
# -----
# - aws_region: ap-northeast-1
# - aws_keypair_name: 
# - rhsm_username: 
# - rhsm_passwd: 
# - wordpress_passwd: 
# -----
# - portal_ami_id: ami-0938769ffbe276d3b
# - portal_instance_type: t3.small
# - portal_subnet_id: 
# - portal_security_group_id: 
# - aap_workflow_url: 
# - aap_bearer_token: 
# ----------------------------------------------
- name: Create a JobTemplate 
  hosts: localhost
  tasks:
    - name: Create JobTemplate - Create Managed VMs
      ansible.controller.job_template:
        name: "Create Managed VMs"
        playbook: create_managed_vms.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_environment }}"
        
        # 認証情報 (credentials に修正)
        credentials: 
          - "{{ aws_credential_name }}"
          - "{{ aws_ssh_credential_name }}"
        # Extra variables
        extra_vars:
          aws_region: "{{ aws_region }}"
          aws_keypair_name: "{{ aws_keypair_name }}"
          rhsm_username: "{{ rhsm_username }}"
          rhsm_passwd: "{{ rhsm_passwd }}"
          mysql_root_passwd: "{{ wordpress_passwd }}"
          mysql_wp_passwd: "{{ wordpress_passwd }}"
          wp_admin_password: "{{ wordpress_passwd }}"
        # 起動時の Extra variables プロンプトを ON
        ask_variables_on_launch: false
        # 「権限昇格」を有効化
        privilege_escalation: true
      
    - name: Create JobTemplate - Delete Managed VMs
      ansible.controller.job_template:
        name: "Delete Managed VMs"
        playbook: delete_managed_vms.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_environment }}"
        credentials: 
          - "{{ aws_credential_name }}"

    - name: Create JobTemplate - Create Demo Portal
      ansible.controller.job_template:
        name: "Create Demo Portal"
        playbook: create_demo_portal.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_environment }}"
        credentials: 
          - "{{ aws_credential_name }}"
          - "{{ aws_ssh_credential_name }}"
        extra_vars:
          aws_region: "{{ aws_region }}"
          ami_id: "{{ portal_ami_id }}"
          instance_type: "{{ portal_instance_type }}"
          key_name: "{{ aws_keypair_name }}"
          subnet_id: "{{ portal_subnet_id }}"
          security_group_id: "{{ portal_security_group_id }}"
          aap_workflow_url: "{{ aap_workflow_url }}"
          aap_bearer_token: "{{ aap_bearer_token }}"

    - name: Create JobTemplate - Scan Advisory
      ansible.controller.job_template:
        name: "Scan Advisory"
        playbook: scan_advisory.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_scan }}"
        credentials: 
          - "{{ aws_ssh_credential_name }}"

    - name: Create JobTemplate - Send Slack Scan
      ansible.controller.job_template:
        name: "Send Slack Scan"
        playbook: send_slack_scan.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_scan }}"
        ask_variables_on_launch: true

    - name: Create JobTemplate - Publish_Advisory
      ansible.controller.job_template:
        name: "Publish_Advisory"
        playbook: publish_advisory.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ github_ssh_credential_name }}"
        extra_vars:
          git_repository_url: "{{ git_repository_url }}"
        ask_variables_on_launch: true

    - name: Create JobTemplate - Send Slack Launch
      ansible.controller.job_template:
        name: "Send Slack Launch"
        playbook: send_slack_launch.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        ask_variables_on_launch: true

    - name: Create JobTemplate - Backup VMs
      ansible.controller.job_template:
        name: "Backup VMs"
        playbook: backup_vm.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ aws_credential_name }}"

    - name: Create JobTemplate - Apply Errata to VMs
      ansible.controller.job_template:
        name: "Apply Errata to VMs"
        playbook: apply_errata.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ aws_ssh_credential_name }}"

    - name: Create JobTemplate - Reboot VMs
      ansible.controller.job_template:
        name: "Reboot VMs"
        playbook: reboot_vm.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ aws_credential_name }}"

    - name: Create JobTemplate - Test VMs
      ansible.controller.job_template:
        name: "Test VMs"
        playbook: test_vm.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ aws_ssh_credential_name }}"

    - name: Create JobTemplate - Test App
      ansible.controller.job_template:
        name: "Test App"
        playbook: test_app.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        credentials: 
          - "{{ aws_credential_name }}"

    - name: Create JobTemplate - Send Slack Report
      ansible.controller.job_template:
        name: "Send Slack Report"
        playbook: send_slack_report.yml
        job_type: run
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: present
        execution_environment: "{{ execution_environment_name }}"
        organization: "{{ organization_name }}"
        labels:
          - "{{ label_patch }}"
        ask_variables_on_launch: true
